version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: chromebook-tester:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/chromebook-tester
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: chromebook-mongo
    environment:
      - MONGO_INITDB_DATABASE=chromebook-tester
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local
